// Code generated by bake. DO NOT EDIT.

package models


import (
    "time"
)

// Deposit represents a row from the 'deposit' table.
type Deposit struct {
    Id int `db:"id" json:"id"` // 
    Name string `db:"name" json:"name"` // 21412
    Age *int `db:"age" json:"age"` // 
    CreatedAt *time.Time `db:"created_at" json:"created_at"` // 
}

// TableName returns the name of the table.
func (Deposit) TableName() string {
    return "deposit"
}
